import type { DiscoverProfile, Group, Event } from '@/types';

/** Seed users mirror a full onboarding: identity, comms, comfort, interests, availability, location, bio, WYR, safety, language, chat prefs, theme. */
export const SEED_PROFILES: DiscoverProfile[] = [
  {
    id: 'user-1',
    name: 'Maya Chen',
    email: 'maya@example.com',
    avatar: '',
    photos: [],
    age: 17,
    ageRange: '16-18',
    identity: 'deaf',
    communicationPreferences: ['asl', 'text_only'],
    comfortPreferences: ['small_group', 'quiet_spaces'],
    interests: ['Art', 'Photography', 'Hiking', 'Cooking'],
    languagePreference: 'asl_first',
    fontScale: 'normal',
    themePreference: 'white',
    primaryColor: '#8B5CF6',
    chatPreferences: { pace: 'normal', captionsPreferred: true },
    bio: {
      perfectHangout: 'A quiet coffee shop with great pastries',
      communicationStyle: 'Fluent ASL signer, love visual conversations',
      lookingForFriend: 'explore art galleries and go on nature walks with',
    },
    location: {
      city: '1500 Main St, Dallas, TX 75201, United States',
      address: '1500 Main St, Dallas, TX 75201',
      school: 'North Dallas High School',
      radiusMiles: 15,
      lat: 32.7767,
      lng: -96.797,
    },
    availability: ['weekends', 'after_school'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-01-15T10:00:00Z',
    distance: 3.2,
    matchScore: 92,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'a', wyr3: 'b', wyr4: 'a', wyr5: 'a' },
  },
  {
    id: 'user-2',
    name: 'Jordan Rivera',
    email: 'jordan@example.com',
    avatar: '',
    photos: [],
    age: 16,
    ageRange: '15-17',
    identity: 'hoh',
    communicationPreferences: ['asl', 'lip_reading'],
    comfortPreferences: ['one_on_one', 'small_group'],
    interests: ['Gaming', 'Robotics', 'Coding', 'Anime'],
    languagePreference: 'bilingual',
    fontScale: 'normal',
    themePreference: 'white',
    primaryColor: '#6366F1',
    chatPreferences: { pace: 'fast', captionsPreferred: true },
    bio: {
      perfectHangout: 'Gaming sessions with snacks and good vibes',
      communicationStyle: 'Mix of ASL and lip reading',
      lookingForFriend: 'play games and build cool projects with',
    },
    location: {
      city: '1000 Throckmorton St, Fort Worth, TX 76102, United States',
      address: '1000 Throckmorton St, Fort Worth, TX 76102',
      school: 'R.L. Paschal High School',
      radiusMiles: 20,
      lat: 32.7555,
      lng: -97.3308,
    },
    availability: ['after_school', 'evenings'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-01-20T10:00:00Z',
    distance: 5.7,
    matchScore: 87,
    wouldYouRatherAnswers: { wyr1: 'b', wyr2: 'a', wyr3: 'a', wyr4: 'b', wyr5: 'a' },
  },
  {
    id: 'user-3',
    name: 'Aisha Thompson',
    email: 'aisha@example.com',
    avatar: '',
    photos: [],
    age: 17,
    ageRange: '16-18',
    identity: 'deaf',
    communicationPreferences: ['asl'],
    comfortPreferences: ['big_group', 'small_group'],
    interests: ['Dance', 'Fashion', 'Music', 'Volunteering'],
    languagePreference: 'asl_first',
    fontScale: 'normal',
    themePreference: 'grey',
    primaryColor: '#EC4899',
    chatPreferences: { pace: 'normal', captionsPreferred: true },
    bio: {
      perfectHangout: 'Dance practice then smoothies after',
      communicationStyle: 'ASL is my first language!',
      lookingForFriend: 'dance, shop, and just have fun with',
    },
    location: {
      city: '2000 E Randol Mill Rd, Arlington, TX 76011, United States',
      address: '2000 E Randol Mill Rd, Arlington, TX 76011',
      school: 'Arlington High School',
      radiusMiles: 10,
      lat: 32.7357,
      lng: -97.1081,
    },
    availability: ['weekends', 'anytime'],
    safetySettings: { showToHearingAllies: false, allowGroupInvites: true, showASLLearners: false },
    onboardingComplete: true,
    createdAt: '2024-02-01T10:00:00Z',
    distance: 8.1,
    matchScore: 78,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'b', wyr3: 'b', wyr4: 'a', wyr5: 'b' },
  },
  {
    id: 'user-4',
    name: 'Ethan Park',
    email: 'ethan@example.com',
    avatar: '',
    photos: [],
    age: 16,
    ageRange: '16-17',
    identity: 'hearing_ally',
    communicationPreferences: ['learning_asl', 'text_only'],
    comfortPreferences: ['one_on_one', 'quiet_spaces'],
    interests: ['Reading', 'Science', 'Board Games', 'Nature'],
    languagePreference: 'english',
    fontScale: 'normal',
    themePreference: 'white',
    primaryColor: '#10B981',
    chatPreferences: { pace: 'slow', captionsPreferred: true, notes: 'Prefer typing first while I build ASL confidence' },
    bio: {
      perfectHangout: 'Board game cafe or a quiet park',
      communicationStyle: 'Learning ASL — patient and enthusiastic',
      lookingForFriend: 'practice ASL and explore new hobbies with',
    },
    location: {
      city: '700 Granite Pkwy, Plano, TX 75024, United States',
      address: '700 Granite Pkwy, Plano, TX 75024',
      school: 'Plano West Senior High School',
      radiusMiles: 15,
      lat: 33.0198,
      lng: -96.6989,
    },
    availability: ['weekends', 'evenings'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-02-10T10:00:00Z',
    distance: 12.4,
    matchScore: 71,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'a', wyr3: 'a', wyr4: 'a', wyr5: 'b' },
  },
  {
    id: 'user-5',
    name: 'Lily Nguyen',
    email: 'lily@example.com',
    avatar: '',
    photos: [],
    age: 15,
    ageRange: '15-16',
    identity: 'deaf',
    communicationPreferences: ['asl', 'written_notes'],
    comfortPreferences: ['small_group', 'quiet_spaces'],
    interests: ['Writing', 'Yoga', 'Pets', 'Cooking'],
    languagePreference: 'asl_first',
    fontScale: 'large',
    themePreference: 'white',
    primaryColor: '#8B5CF6',
    chatPreferences: { pace: 'slow', captionsPreferred: true },
    bio: {
      perfectHangout: 'Cozy bookstore vibes with a good friend',
      communicationStyle: 'Native ASL, also love passing notes',
      lookingForFriend: 'write stories and cook new recipes with',
    },
    location: {
      city: "2901 N O'Connor Rd, Irving, TX 75062, United States",
      address: "2901 N O'Connor Rd, Irving, TX 75062",
      school: 'Irving High School',
      radiusMiles: 10,
      lat: 32.814,
      lng: -96.9489,
    },
    availability: ['after_school', 'weekends'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: false, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-02-15T10:00:00Z',
    distance: 6.8,
    matchScore: 85,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'a', wyr3: 'b', wyr4: 'a', wyr5: 'a' },
  },
  {
    id: 'user-6',
    name: 'Marcus Johnson',
    email: 'marcus@example.com',
    avatar: '',
    photos: [],
    age: 18,
    ageRange: '17-18',
    identity: 'hoh',
    communicationPreferences: ['lip_reading', 'text_only', 'learning_asl'],
    comfortPreferences: ['big_group', 'one_on_one'],
    interests: ['Sports', 'Movies', 'Nature'],
    languagePreference: 'bilingual',
    fontScale: 'normal',
    themePreference: 'black',
    primaryColor: '#F59E0B',
    chatPreferences: { pace: 'normal', captionsPreferred: false },
    bio: {
      perfectHangout: 'Pickup sports game then watching movies',
      communicationStyle: 'Lip reading mostly, picking up ASL',
      lookingForFriend: 'play sports and watch movies with',
    },
    location: {
      city: '2345 Forest Ln, Garland, TX 75042, United States',
      address: '2345 Forest Ln, Garland, TX 75042',
      school: 'Garland High School',
      radiusMiles: 20,
      lat: 32.9126,
      lng: -96.6389,
    },
    availability: ['anytime'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-01T10:00:00Z',
    distance: 9.5,
    matchScore: 74,
    wouldYouRatherAnswers: { wyr1: 'b', wyr2: 'a', wyr3: 'a', wyr4: 'b', wyr5: 'b' },
  },
  {
    id: 'user-7',
    name: 'Sofia Martinez',
    email: 'sofia@example.com',
    avatar: '',
    photos: [],
    age: 16,
    ageRange: '15-17',
    identity: 'deaf',
    communicationPreferences: ['asl', 'text_only'],
    comfortPreferences: ['one_on_one', 'small_group'],
    interests: ['Movies', 'Anime', 'Cooking', 'Pets'],
    languagePreference: 'asl_first',
    fontScale: 'normal',
    themePreference: 'white',
    primaryColor: '#A855F7',
    chatPreferences: { pace: 'normal', captionsPreferred: true },
    bio: {
      perfectHangout: 'Watching a new movie with good captions then grabbing tacos after',
      communicationStyle: 'ASL first, texting is cool too',
      lookingForFriend: 'hang out around Dallas and try new food spots with',
    },
    location: {
      city: '1200 S Haskell Ave, Dallas, TX 75223, United States',
      address: '1200 S Haskell Ave, Dallas, TX 75223',
      school: 'Woodrow Wilson High School',
      radiusMiles: 12,
      lat: 32.7767,
      lng: -96.797,
    },
    availability: ['evenings', 'weekends'],
    safetySettings: { showToHearingAllies: false, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-05T10:00:00Z',
    distance: 2.3,
    matchScore: 80,
    wouldYouRatherAnswers: { wyr1: 'b', wyr2: 'a', wyr3: 'b', wyr4: 'b', wyr5: 'a' },
  },
  {
    id: 'user-8',
    name: 'Noah Williams',
    email: 'noah@example.com',
    avatar: '',
    photos: [],
    age: 17,
    ageRange: '16-18',
    identity: 'hoh',
    communicationPreferences: ['lip_reading', 'text_only'],
    comfortPreferences: ['small_group', 'quiet_spaces'],
    interests: ['Gaming', 'Board Games', 'Science', 'Nature'],
    languagePreference: 'bilingual',
    fontScale: 'normal',
    themePreference: 'grey',
    primaryColor: '#3B82F6',
    chatPreferences: { pace: 'normal', captionsPreferred: true },
    bio: {
      perfectHangout: 'Chill game night at home or walking around White Rock Lake',
      communicationStyle: 'Lip reading + texting, always patient',
      lookingForFriend: 'explore Dallas and play co-op games with',
    },
    location: {
      city: '9930 White Rock Trail, Dallas, TX 75238, United States',
      address: '9930 White Rock Trail, Dallas, TX 75238',
      school: 'Lake Highlands High School',
      radiusMiles: 10,
      lat: 32.823,
      lng: -96.75,
    },
    availability: ['after_school', 'evenings'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-08T10:00:00Z',
    distance: 4.1,
    matchScore: 77,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'b', wyr3: 'a', wyr4: 'b', wyr5: 'b' },
  },
  {
    id: 'user-9',
    name: 'Priya Patel',
    email: 'priya@example.com',
    avatar: '',
    photos: [],
    age: 16,
    ageRange: '16-18',
    identity: 'deaf',
    communicationPreferences: ['asl', 'written_notes'],
    comfortPreferences: ['one_on_one', 'quiet_spaces'],
    interests: ['Science', 'Astronomy', 'Photography', 'Reading'],
    languagePreference: 'asl_first',
    fontScale: 'large',
    themePreference: 'white',
    primaryColor: '#0EA5E9',
    chatPreferences: { pace: 'slow', captionsPreferred: true },
    bio: {
      perfectHangout: 'A museum trip or stargazing with warm drinks',
      communicationStyle: 'ASL + notes when it gets loud',
      lookingForFriend: 'learn new things and take photos with',
    },
    location: {
      city: '900 S Plano Rd, Richardson, TX 75081, United States',
      address: '900 S Plano Rd, Richardson, TX 75081',
      school: 'Richardson High School',
      radiusMiles: 15,
      lat: 32.9483,
      lng: -96.7299,
    },
    availability: ['evenings', 'weekends'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-12T10:00:00Z',
    distance: 7.6,
    matchScore: 79,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'a', wyr3: 'a', wyr4: 'b', wyr5: 'a' },
  },
  {
    id: 'user-10',
    name: 'Kai Nguyen',
    email: 'kai@example.com',
    avatar: '',
    photos: [],
    age: 15,
    ageRange: '15-17',
    identity: 'hoh',
    communicationPreferences: ['text_only', 'lip_reading'],
    comfortPreferences: ['small_group', 'quiet_spaces'],
    interests: ['Coding', 'Robotics', 'Gaming', 'Science'],
    languagePreference: 'english',
    fontScale: 'normal',
    themePreference: 'white',
    primaryColor: '#6366F1',
    chatPreferences: { pace: 'fast', captionsPreferred: true },
    bio: {
      perfectHangout: 'Building something small, then a chill game night',
      communicationStyle: 'Text-first, lip reading if needed',
      lookingForFriend: 'work on projects and game with',
    },
    location: {
      city: '6505 Custer Rd, Plano, TX 75023, United States',
      address: '6505 Custer Rd, Plano, TX 75023',
      school: 'Plano Senior High School',
      radiusMiles: 18,
      lat: 33.0198,
      lng: -96.6989,
    },
    availability: ['after_school', 'evenings'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-14T10:00:00Z',
    distance: 12.9,
    matchScore: 76,
    wouldYouRatherAnswers: { wyr1: 'b', wyr2: 'b', wyr3: 'a', wyr4: 'a', wyr5: 'b' },
  },
  {
    id: 'user-11',
    name: 'Zoe Brooks',
    email: 'zoe@example.com',
    avatar: '',
    photos: [],
    age: 17,
    ageRange: '16-18',
    identity: 'hearing_ally',
    communicationPreferences: ['learning_asl', 'text_only'],
    comfortPreferences: ['one_on_one', 'small_group'],
    interests: ['Art', 'Crafts', 'Theater', 'Music'],
    languagePreference: 'bilingual',
    fontScale: 'normal',
    themePreference: 'white',
    primaryColor: '#EC4899',
    chatPreferences: { pace: 'normal', captionsPreferred: true },
    bio: {
      perfectHangout: 'Craft night with playlists and snacks',
      communicationStyle: 'Learning ASL and always happy to text',
      lookingForFriend: 'go to shows and make art with',
    },
    location: {
      city: '3000 N MacArthur Blvd, Irving, TX 75062, United States',
      address: '3000 N MacArthur Blvd, Irving, TX 75062',
      school: 'MacArthur High School',
      radiusMiles: 14,
      lat: 32.814,
      lng: -96.9489,
    },
    availability: ['weekends', 'evenings'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-16T10:00:00Z',
    distance: 10.8,
    matchScore: 70,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'b', wyr3: 'b', wyr4: 'a', wyr5: 'a' },
  },
  {
    id: 'user-12',
    name: 'Amir Hassan',
    email: 'amir@example.com',
    avatar: '',
    photos: [],
    age: 18,
    ageRange: '17-18',
    identity: 'deaf',
    communicationPreferences: ['asl', 'text_only'],
    comfortPreferences: ['big_group', 'small_group'],
    interests: ['Travel', 'Movies', 'Cooking', 'Nature'],
    languagePreference: 'asl_first',
    fontScale: 'normal',
    themePreference: 'grey',
    primaryColor: '#14B8A6',
    chatPreferences: { pace: 'normal', captionsPreferred: true },
    bio: {
      perfectHangout: 'Trying a new food spot then a walk somewhere scenic',
      communicationStyle: 'ASL first, texting for quick plans',
      lookingForFriend: 'explore new places and eat good food with',
    },
    location: {
      city: '2101 S Collins St, Arlington, TX 76010, United States',
      address: '2101 S Collins St, Arlington, TX 76010',
      school: 'Bowie High School',
      radiusMiles: 20,
      lat: 32.7357,
      lng: -97.1081,
    },
    availability: ['weekends', 'anytime'],
    safetySettings: { showToHearingAllies: false, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-18T10:00:00Z',
    distance: 16.2,
    matchScore: 73,
    wouldYouRatherAnswers: { wyr1: 'b', wyr2: 'a', wyr3: 'b', wyr4: 'b', wyr5: 'a' },
  },
  {
    id: 'user-13',
    name: 'Ella Kim',
    email: 'ella@example.com',
    avatar: '',
    photos: [],
    age: 16,
    ageRange: '15-17',
    identity: 'hoh',
    communicationPreferences: ['written_notes', 'text_only', 'learning_asl'],
    comfortPreferences: ['one_on_one', 'quiet_spaces'],
    interests: ['Yoga', 'Sports', 'Pets', 'Nature'],
    languagePreference: 'bilingual',
    fontScale: 'normal',
    themePreference: 'white',
    primaryColor: '#F472B6',
    chatPreferences: { pace: 'slow', captionsPreferred: true, notes: 'Quiet spaces help me follow best' },
    bio: {
      perfectHangout: 'Yoga class then hanging with pets at a park',
      communicationStyle: 'Notes/text, and practicing ASL',
      lookingForFriend: 'stay active and spend time outside with',
    },
    location: {
      city: '1255 W Trinity Mills Rd, Carrollton, TX 75006, United States',
      address: '1255 W Trinity Mills Rd, Carrollton, TX 75006',
      school: 'Newman Smith High School',
      radiusMiles: 12,
      lat: 32.9756,
      lng: -96.8897,
    },
    availability: ['after_school', 'weekends'],
    safetySettings: { showToHearingAllies: true, allowGroupInvites: false, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-20T10:00:00Z',
    distance: 11.3,
    matchScore: 68,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'a', wyr3: 'a', wyr4: 'a', wyr5: 'b' },
  },
  {
    id: 'user-14',
    name: 'Diego Alvarez',
    email: 'diego@example.com',
    avatar: '',
    photos: [],
    age: 17,
    ageRange: '16-18',
    identity: 'deaf',
    communicationPreferences: ['asl'],
    comfortPreferences: ['small_group', 'big_group'],
    interests: ['Dance', 'Music', 'Fashion', 'Movies'],
    languagePreference: 'asl_first',
    fontScale: 'normal',
    themePreference: 'black',
    primaryColor: '#8B5CF6',
    chatPreferences: { pace: 'fast', captionsPreferred: true },
    bio: {
      perfectHangout: 'Dance practice, then finding a new movie to watch',
      communicationStyle: 'ASL only — expressive and visual',
      lookingForFriend: 'dance, share playlists, and hype each other up with',
    },
    location: {
      city: '7777 Forney Rd, Dallas, TX 75227, United States',
      address: '7777 Forney Rd, Dallas, TX 75227',
      school: 'Skyline High School',
      radiusMiles: 15,
      lat: 32.7767,
      lng: -96.797,
    },
    availability: ['evenings', 'weekends'],
    safetySettings: { showToHearingAllies: false, allowGroupInvites: true, showASLLearners: false },
    onboardingComplete: true,
    createdAt: '2024-03-22T10:00:00Z',
    distance: 3.9,
    matchScore: 81,
    wouldYouRatherAnswers: { wyr1: 'a', wyr2: 'b', wyr3: 'b', wyr4: 'a', wyr5: 'b' },
  },
];

export const SEED_GROUPS: Group[] = [
  {
    id: 'group-1',
    name: 'Deaf Teens DFW',
    description:
      'A community for Deaf and HoH teens in the Dallas-Fort Worth area. Share experiences, plan meetups, and make lasting friendships!',
    city: 'Dallas-Fort Worth, TX',
    tags: ['Deaf Community', 'Teens', 'Social', 'DFW'],
    rules: ['Be respectful', 'ASL-friendly communication', 'No bullying', 'Keep it fun!'],
    type: 'public',
    members: ['user-1', 'user-2', 'user-3', 'user-5'],
    admins: ['user-1'],
    pinnedPosts: [
      {
        id: 'post-1',
        groupId: 'group-1',
        authorId: 'user-1',
        content: 'Welcome to Deaf Teens DFW! Introduce yourself and share your favorite hobby.',
        isPinned: true,
        createdAt: '2024-01-15T10:00:00Z',
      },
    ],
    avatar: '',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'group-2',
    name: 'ASL Learners + Deaf Friends',
    description:
      'A supportive space where ASL learners can practice with Deaf friends. Everyone is welcome — patience and kindness are key!',
    city: 'Dallas, TX',
    tags: ['ASL', 'Learning', 'Practice', 'Inclusive'],
    rules: ['Be patient with learners', 'Encourage each other', 'No judgment', 'Have fun learning'],
    type: 'public',
    members: ['user-1', 'user-4', 'user-5'],
    admins: ['user-4'],
    pinnedPosts: [],
    avatar: '',
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'group-3',
    name: 'Robotics + STEM',
    description:
      'For Deaf/HoH students passionate about robotics, coding, science, and tech. Share projects, ask questions, and collaborate!',
    city: 'Fort Worth, TX',
    tags: ['STEM', 'Robotics', 'Coding', 'Science'],
    rules: ['Share your projects', 'Help each other', 'Stay on topic', 'No spam'],
    type: 'request_to_join',
    members: ['user-2', 'user-4'],
    admins: ['user-2'],
    pinnedPosts: [],
    avatar: '',
    createdAt: '2024-02-15T10:00:00Z',
  },
];

export const SEED_EVENTS: Event[] = [
  {
    id: 'event-1',
    title: 'ASL Game Night',
    description:
      'Join us for a fun evening of board games and card games — all in ASL! Snacks provided. Beginners welcome.',
    location: 'Dallas Community Center, Dallas TX',
    date: '2026-03-20',
    time: '6:00 PM',
    tags: ['ASL-friendly', 'Quiet Place', 'Games'],
    communicationSupport: 'ASL interpreters available',
    organizerId: 'user-1',
    rsvps: ['user-1', 'user-2', 'user-5'],
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'event-2',
    title: 'Deaf Coffee Chat',
    description:
      'Casual meet-up at a deaf-friendly cafe. Come hang out, practice ASL, or just chill with new friends!',
    location: 'Quiet Beans Cafe, Fort Worth TX',
    date: '2026-03-25',
    time: '3:00 PM',
    tags: ['Quiet Place', 'ASL-friendly', 'Casual'],
    organizerId: 'user-3',
    rsvps: ['user-3', 'user-1'],
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'event-3',
    title: 'STEM Workshop: Intro to Arduino',
    description:
      'Hands-on workshop building simple circuits with Arduino. Captioned presentations and visual instructions provided.',
    location: 'Plano Library MakerSpace, Plano TX',
    date: '2026-04-05',
    time: '10:00 AM',
    tags: ['Captioned Venue', 'STEM', 'Workshop'],
    communicationSupport: 'Captioned slides, visual demos',
    organizerId: 'user-2',
    rsvps: ['user-2', 'user-4'],
    createdAt: '2024-03-10T10:00:00Z',
  },
];
